### ISSUE TITLE
unable to get bytemask working.

### ISSUE THREAD

**Issue by aliakhgar** [PatilShreyas/bytemask#13]
Hi, 
I've added bytemask to my android project but after exporting in both debug and release and opening in jadx, I can see that none of my strings are encrypted by bytemask.

Here is My gradle plugins on top of my gradle app level file.
```
plugins{
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id('com.google.gms.google-services')
    id("com.facebook.react")
    id("dev.shreyaspatil.bytemask.plugin") version "1.0.0-alpha02"
}
```
 here is my bytemask config at the end of app level gradle.
```
bytemaskConfig {
    defaultPropertiesFileName.set("bytemask.properties")
    className.set("BytemaskConfig")
    configure("debug") {
        enableEncryption.set(true)

        encryptionKeySource.set(new KeySource.SigningConfig("debug"))
    }

    configure("release") {
        enableEncryption.set(true)

        encryptionKeySource.set(new KeySource.SigningConfig("release"))
    }
}
```

And here is my jadx screenshot.
<img width="994" alt="Screenshot 1403-04-04 at 9 45 11 at night" src="https://github.com/PatilShreyas/bytemask/assets/19927869/3da1533f-3ec9-4bf9-8c94-fc4f2d79c97f">

What am i missing out here, respectively?
gradle task :bytemaskDebug is being executed fine also.

**Comment by PatilShreyas** [comment]
@aliakhgar the screenshot you attached here, I'm just seeing MainApplication file. Can you check the content of `BytemaskConfig`?

So it just masks the strings present in .properties file into a separate class altogether.

**Comment by PatilShreyas** [comment]
Thanks. Feel free to discuss again.
