### ISSUE TITLE
dollar sign '$' isn't escaped when generating BytemaskConfig for unencrypted strings 

### ISSUE THREAD

**Issue by mr3y-the-programmer** [PatilShreyas/bytemask#15]
Hi, I'm trying this plugin in a project and it works great so far but I found a bug that fails the project compilation because it is invalid kotlin syntax.

Basically, if you have a secret string like this in `bytemask.properties` file:
```properties
API_KEY=AI984013oi$ndh48
```
Assuming the encryption is disabled for a particular build variant (say "debug" for example), then the generated `BytemaskConfig` for that variant will look like this:
```kotlin
object BytemaskConfig {
    @JvmStatic
    @get:JvmName("apiKey")
    val API_KEY by lazy { "AI984013oi$ndh48" }
}
```
which isn't a valid kotlin code because the '$' isn't escaped properly

**Comment by PatilShreyas** [comment]
Thanks @mr3y-the-programmer for reporting the issue. Will take a look into this.
