### ISSUE TITLE
Incompatible with `applicationIdSuffix`

### ISSUE THREAD

**Issue by matejsemancik** [PatilShreyas/bytemask#8]
The generated classes have package resolved from `applicationId` + `applicationIdSuffix` which breaks compatibility between different build variants.

For example:

```kotlin
// app module build.gradle.kts

android {
  namespace = "com.example.app.android"

  defaultConfig {
    applicationId = "com.example.app"
  }

  buildTypes {
    debug {
      applicationIdSuffix = ".debug"
    }
    release {
      applicationIdSuffix = ".release"
    }
  }
}

bytemaskConfig {
  className.set("BytemaskConfig")
}
```

- For `debug` build type, the generated class will be generated as `com.example.app.debug.BytemaskConfig`
- For `release` build type, the generated class will be generated as `com.example.app.release.BytemaskConfig`

This breaks binary compatibility between build variants and project will not compile after switching between build types.

I think the solution would be either to:
- generate class in namespace package (like AGP does with BuildConfig), or
- let user specify package for generated class

**Comment by PatilShreyas** [comment]
Thanks for raising this issue and helping to make it better.

**Comment by PatilShreyas** [comment]
We'll plan it for upcoming alpha version: `1.0.0-alpha02`
